#ifdef NDEBUG
#undef NDEBUG
#endif

#include "phone_forward.h"

#include <assert.h>
#include <string.h>

#define MAX_LEN 30
int main() {
  char num1[MAX_LEN + 1], num2[MAX_LEN + 1];
  PhoneForward *pf;
  PhoneNumbers *pnum;
  pf = phfwdNew();
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "022");
  assert(strcmp(phnumGet(pnum, 0), "022") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01");
  phfwdRemove(pf, "0221");
  phfwdRemove(pf, "021");
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22122");
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01020");
  phfwdRemove(pf, "02110");
  strcpy(num1, "2");
  strcpy(num2, "020");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "20122");
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "102") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20220");
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "1021");
  phfwdRemove(pf, "21");
  pnum = phfwdGet(pf, "12011");
  assert(strcmp(phnumGet(pnum, 0), "12011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "121");
  pnum = phfwdGet(pf, "11200");
  assert(strcmp(phnumGet(pnum, 0), "11200") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1211");
  assert(strcmp(phnumGet(pnum, 0), "1211") == 0);
  phnumDelete(pnum);
  strcpy(num1, "00022");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20010");
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "1201");
  assert(strcmp(phnumGet(pnum, 0), "1201") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2002");
  strcpy(num2, "12212");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "21001");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "001");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "200");
  pnum = phfwdGet(pf, "12120");
  assert(strcmp(phnumGet(pnum, 0), "12120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "11212");
  strcpy(num1, "201");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00");
  phfwdRemove(pf, "20012");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "1011");
  phfwdRemove(pf, "00");
  pnum = phfwdGet(pf, "0010");
  assert(strcmp(phnumGet(pnum, 0), "0010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0122");
  assert(strcmp(phnumGet(pnum, 0), "0122") == 0);
  phnumDelete(pnum);
  strcpy(num1, "210");
  strcpy(num2, "1012");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "22121");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "022");
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "0201") == 0);
  phnumDelete(pnum);
  strcpy(num1, "012");
  strcpy(num2, "1120");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "201");
  phnumDelete(pnum);
  phfwdRemove(pf, "02");
  strcpy(num1, "0");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "201");
  phfwdRemove(pf, "0210");
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "221212") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "111");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "012");
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1101");
  assert(strcmp(phnumGet(pnum, 0), "1101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "0");
  strcpy(num2, "2010");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02201");
  strcpy(num2, "0111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1121");
  assert(strcmp(phnumGet(pnum, 0), "1121") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "11");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01120");
  assert(strcmp(phnumGet(pnum, 0), "20101120") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0022");
  assert(strcmp(phnumGet(pnum, 0), "2010022") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10222");
  strcpy(num2, "202");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20");
  phfwdRemove(pf, "2100");
  phfwdRemove(pf, "2");
  strcpy(num1, "00");
  strcpy(num2, "0200");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "11101");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "102");
  strcpy(num2, "001");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "011");
  strcpy(num1, "00122");
  strcpy(num2, "20120");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2010");
  assert(strcmp(phnumGet(pnum, 0), "0210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0000");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "2002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20021");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "201");
  strcpy(num1, "101");
  strcpy(num2, "0001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "001");
  assert(strcmp(phnumGet(pnum, 0), "02001") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "20020") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "2101");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0000");
  strcpy(num2, "10021");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "100");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "202");
  assert(strcmp(phnumGet(pnum, 0), "022") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "1201a");
  assert(phfwdAdd(pf, num1, num2) == false);
  phfwdRemove(pf, "112");
  pnum = phfwdGet(pf, "12021");
  assert(strcmp(phnumGet(pnum, 0), "0021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "120");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "1");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0020");
  pnum = phfwdGet(pf, "212");
  assert(strcmp(phnumGet(pnum, 0), "212") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10201");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2122");
  assert(strcmp(phnumGet(pnum, 0), "2122") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "2011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1212");
  strcpy(num1, "12022");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "201");
  phfwdRemove(pf, "121");
  pnum = phfwdGet(pf, "120");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2011");
  strcpy(num2, "21100");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "20111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1020");
  assert(strcmp(phnumGet(pnum, 0), "0010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1020");
  assert(strcmp(phnumGet(pnum, 0), "0010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00010");
  assert(strcmp(phnumGet(pnum, 0), "00010") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "022");
  phfwdRemove(pf, "111");
  strcpy(num1, "22");
  strcpy(num2, "201");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "01020");
  phfwdRemove(pf, "21121");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "11");
  strcpy(num1, "22");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "102");
  phfwdRemove(pf, "0022");
  phfwdRemove(pf, "0");
  strcpy(num1, "2220");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "100");
  strcpy(num1, "21");
  strcpy(num2, "11220");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11222");
  strcpy(num1, "2");
  strcpy(num2, "101");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "020");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10102");
  strcpy(num1, "222");
  strcpy(num2, "2002");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2022");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "01101");
  strcpy(num1, "21201");
  strcpy(num2, "11202");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11010");
  assert(strcmp(phnumGet(pnum, 0), "11010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "002") == 0);
  phnumDelete(pnum);
  strcpy(num1, "211");
  strcpy(num2, "11020");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  strcpy(num1, "0");
  strcpy(num2, "121");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22201");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10102");
  strcpy(num2, "101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22210");
  assert(strcmp(phnumGet(pnum, 0), "22210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "012");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "211");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01210");
  assert(strcmp(phnumGet(pnum, 0), "1010") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "10012");
  assert(strcmp(phnumGet(pnum, 0), "10012") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "22");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02010");
  assert(strcmp(phnumGet(pnum, 0), "02010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "10220");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02002");
  assert(strcmp(phnumGet(pnum, 0), "02002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20220");
  pnum = phfwdGet(pf, "1210");
  assert(strcmp(phnumGet(pnum, 0), "1210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "2221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "12") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "112");
  assert(strcmp(phnumGet(pnum, 0), "112") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2100");
  assert(strcmp(phnumGet(pnum, 0), "2100") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01110");
  phfwdRemove(pf, "200");
  pnum = phfwdGet(pf, "202");
  assert(strcmp(phnumGet(pnum, 0), "102202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2212");
  phfwdRemove(pf, "2211");
  strcpy(num1, "1112");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0020");
  phfwdRemove(pf, "01");
  pnum = phfwdGet(pf, "0a1");
  assert(phnumGet(pnum, 0) == NULL);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1100");
  assert(strcmp(phnumGet(pnum, 0), "1100") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2201");
  assert(strcmp(phnumGet(pnum, 0), "222101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "0222");
  assert(strcmp(phnumGet(pnum, 0), "0222") == 0);
  phnumDelete(pnum);
  strcpy(num1, "101");
  strcpy(num2, "1211");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1210");
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "1002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10020");
  assert(strcmp(phnumGet(pnum, 0), "1002020") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1220");
  phfwdRemove(pf, "21110");
  strcpy(num1, "12");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "111");
  strcpy(num1, "210");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "221");
  assert(strcmp(phnumGet(pnum, 0), "22211") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "2211");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10202");
  assert(strcmp(phnumGet(pnum, 0), "1002202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "10");
  strcpy(num1, "01");
  strcpy(num2, "1110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20220");
  strcpy(num2, "2210");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12111");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20101");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  strcpy(num1, "111");
  strcpy(num2, "1122");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10102");
  pnum = phfwdGet(pf, "022");
  assert(strcmp(phnumGet(pnum, 0), "221122") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0000");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "20010");
  strcpy(num1, "20");
  strcpy(num2, "1112");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21022");
  phfwdRemove(pf, "2021");
  strcpy(num1, "2202");
  strcpy(num2, "01210");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20011");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22010");
  assert(strcmp(phnumGet(pnum, 0), "22010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "01");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "221");
  assert(strcmp(phnumGet(pnum, 0), "221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "1210");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "001");
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "22110") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11");
  strcpy(num2, "10120");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2111");
  assert(strcmp(phnumGet(pnum, 0), "2111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "202");
  strcpy(num1, "122");
  strcpy(num2, "21011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12");
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "021");
  phfwdRemove(pf, "01212");
  strcpy(num1, "01110");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20021");
  assert(strcmp(phnumGet(pnum, 0), "1112021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "21001");
  assert(strcmp(phnumGet(pnum, 0), "21001") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "110");
  pnum = phfwdGet(pf, "2200");
  assert(strcmp(phnumGet(pnum, 0), "2200") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2102");
  pnum = phfwdGet(pf, "2002");
  assert(strcmp(phnumGet(pnum, 0), "111202") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "000");
  assert(strcmp(phnumGet(pnum, 0), "000") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "00");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "12000");
  assert(strcmp(phnumGet(pnum, 0), "1210000") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2000");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "010");
  assert(strcmp(phnumGet(pnum, 0), "010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "212");
  strcpy(num2, "1010");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "102");
  strcpy(num2, "12011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "001");
  assert(strcmp(phnumGet(pnum, 0), "0111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "21");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10121");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "0112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22");
  strcpy(num1, "11");
  strcpy(num2, "2221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00222");
  assert(strcmp(phnumGet(pnum, 0), "011222") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2212");
  assert(strcmp(phnumGet(pnum, 0), "2212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00");
  strcpy(num1, "0100");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0221");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "121");
  assert(strcmp(phnumGet(pnum, 0), "12101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "110");
  pnum = phfwdGet(pf, "010");
  assert(strcmp(phnumGet(pnum, 0), "010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "10112");
  strcpy(num1, "11");
  strcpy(num2, "2100");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0201");
  assert(strcmp(phnumGet(pnum, 0), "0201") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "02001");
  strcpy(num1, "0");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "000");
  assert(strcmp(phnumGet(pnum, 0), "000") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "00200");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "021");
  strcpy(num1, "00020");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "021");
  assert(strcmp(phnumGet(pnum, 0), "021") == 0);
  phnumDelete(pnum);
  strcpy(num1, "102");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "111");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1021");
  phfwdRemove(pf, "120");
  phfwdRemove(pf, "10202");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "102");
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "1211");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10200");
  strcpy(num2, "20221");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1021");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2121");
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1122");
  assert(strcmp(phnumGet(pnum, 0), "210022") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22221");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "01100");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0211");
  strcpy(num2, "222");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "100");
  strcpy(num1, "12");
  strcpy(num2, "21020");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00012");
  assert(strcmp(phnumGet(pnum, 0), "01100012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "01") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11110");
  assert(strcmp(phnumGet(pnum, 0), "110") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "220");
  assert(strcmp(phnumGet(pnum, 0), "220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "0201");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12221");
  phfwdRemove(pf, "12011");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "00");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10");
  strcpy(num2, "2022");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "210");
  phfwdRemove(pf, "2");
  strcpy(num1, "0110");
  strcpy(num2, "02211");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12");
  strcpy(num2, "01201");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0222");
  strcpy(num1, "21001");
  strcpy(num2, "00201");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11");
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "11201");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "2202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "110");
  pnum = phfwdGet(pf, "0210");
  assert(strcmp(phnumGet(pnum, 0), "0210") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21");
  strcpy(num1, "2012");
  strcpy(num2, "00000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20");
  strcpy(num2, "00111");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01102");
  strcpy(num2, "000");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "2202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "00200");
  strcpy(num2, "0120");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0121");
  strcpy(num2, "11210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "01") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "2021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  phnumDelete(pnum);
  phfwdRemove(pf, "010");
  strcpy(num1, "2");
  strcpy(num2, "221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  strcpy(num1, "220");
  strcpy(num2, "2000");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2020");
  assert(strcmp(phnumGet(pnum, 0), "202120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "2212") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0122");
  strcpy(num2, "202");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2201");
  strcpy(num2, "202");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22220");
  strcpy(num1, "12");
  strcpy(num2, "02121");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2202");
  pnum = phfwdGet(pf, "0020");
  assert(strcmp(phnumGet(pnum, 0), "22020") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "012");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "2212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12022");
  strcpy(num1, "00");
  strcpy(num2, "11001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0211");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "201");
  strcpy(num2, "2000");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12210");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "12011");
  assert(strcmp(phnumGet(pnum, 0), "02121011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "110");
  pnum = phfwdGet(pf, "02");
  phnumDelete(pnum);
  phfwdRemove(pf, "10221");
  phfwdRemove(pf, "202");
  pnum = phfwdGet(pf, "2111");
  assert(strcmp(phnumGet(pnum, 0), "2111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "101");
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "200");
  phfwdRemove(pf, "00202");
  strcpy(num1, "012");
  strcpy(num2, "11010");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "21");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "020");
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1021");
  assert(strcmp(phnumGet(pnum, 0), "012021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "202");
  assert(strcmp(phnumGet(pnum, 0), "202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "121");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "000");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12");
  phnumDelete(pnum);
  phfwdRemove(pf, "0010");
  strcpy(num1, "11");
  strcpy(num2, "002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20102");
  assert(strcmp(phnumGet(pnum, 0), "20102") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "202");
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "222");
  assert(strcmp(phnumGet(pnum, 0), "222") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1002");
  pnum = phfwdGet(pf, "2102");
  assert(strcmp(phnumGet(pnum, 0), "2002") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  strcpy(num1, "121");
  strcpy(num2, "0112");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20101");
  assert(strcmp(phnumGet(pnum, 0), "20101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "0221");
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "02112");
  phfwdRemove(pf, "00202");
  pnum = phfwdGet(pf, "022");
  assert(strcmp(phnumGet(pnum, 0), "022") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "01202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2011");
  strcpy(num2, "22021");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "1100");
  pnum = phfwdGet(pf, "1012");
  assert(strcmp(phnumGet(pnum, 0), "012012") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1010");
  strcpy(num1, "022");
  strcpy(num2, "21012");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "2212");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11212");
  pnum = phfwdGet(pf, "221");
  assert(strcmp(phnumGet(pnum, 0), "221221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "200");
  strcpy(num2, "211");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "0102");
  strcpy(num1, "0");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "21210");
  assert(strcmp(phnumGet(pnum, 0), "20210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22101");
  strcpy(num2, "12011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20");
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "0120");
  phfwdRemove(pf, "2011");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "002") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "120");
  assert(strcmp(phnumGet(pnum, 0), "021210") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12111");
  phfwdRemove(pf, "2101");
  strcpy(num1, "1001");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "20121");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "020");
  assert(strcmp(phnumGet(pnum, 0), "020") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "002");
  strcpy(num1, "10211");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "201210") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "200");
  strcpy(num1, "00100");
  strcpy(num2, "10122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "100");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "220");
  strcpy(num1, "10");
  strcpy(num2, "20021");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  strcpy(num1, "21");
  strcpy(num2, "12002");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  phfwdRemove(pf, "2");
  strcpy(num1, "100");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "220");
  assert(strcmp(phnumGet(pnum, 0), "220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0210");
  strcpy(num2, "0122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22100");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "200");
  assert(strcmp(phnumGet(pnum, 0), "200") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11");
  phnumDelete(pnum);
  strcpy(num1, "1201");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "012");
  assert(strcmp(phnumGet(pnum, 0), "012") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "00");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "000");
  pnum = phfwdGet(pf, "1100");
  assert(strcmp(phnumGet(pnum, 0), "00200") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20102");
  strcpy(num2, "2221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "201211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "001");
  phfwdRemove(pf, "11020");
  phfwdRemove(pf, "22002");
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "21");
  pnum = phfwdGet(pf, "221");
  assert(strcmp(phnumGet(pnum, 0), "221") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02020");
  assert(strcmp(phnumGet(pnum, 0), "02020") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "000");
  assert(strcmp(phnumGet(pnum, 0), "0110") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "10000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "202");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "12001");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20221");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "011");
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "002");
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "122");
  strcpy(num1, "0");
  strcpy(num2, "2000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "201");
  strcpy(num2, "010");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0202");
  strcpy(num2, "01122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0221");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0222");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "02102");
  assert(strcmp(phnumGet(pnum, 0), "20002102") == 0);
  phnumDelete(pnum);
  strcpy(num1, "102");
  strcpy(num2, "1002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20021");
  phfwdRemove(pf, "221");
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "20002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "110");
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "20001") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "011");
  pnum = phfwdGet(pf, "2201");
  assert(strcmp(phnumGet(pnum, 0), "2201") == 0);
  phnumDelete(pnum);
  strcpy(num1, "102");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11012");
  strcpy(num1, "0202");
  strcpy(num2, "211");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11012");
  strcpy(num1, "0002");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0212");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00201");
  strcpy(num1, "000");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2112");
  assert(strcmp(phnumGet(pnum, 0), "2112") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1202");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02001");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "110");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02000");
  assert(strcmp(phnumGet(pnum, 0), "20002000") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2100");
  strcpy(num2, "1122");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20000");
  strcpy(num1, "11112");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "111");
  strcpy(num2, "0121");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "0210");
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "10022");
  assert(strcmp(phnumGet(pnum, 0), "120010022") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21");
  strcpy(num1, "0120");
  strcpy(num2, "10011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1002");
  assert(strcmp(phnumGet(pnum, 0), "12001002") == 0);
  phnumDelete(pnum);
  strcpy(num1, "100");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "001");
  assert(strcmp(phnumGet(pnum, 0), "001") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "0000");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2101");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "120011") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1200");
  assert(strcmp(phnumGet(pnum, 0), "0100") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2022");
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "0121");
  phfwdRemove(pf, "221");
  phfwdRemove(pf, "22121");
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "2020");
  strcpy(num1, "22001");
  strcpy(num2, "12210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "01") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12120");
  assert(strcmp(phnumGet(pnum, 0), "12120") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "011");
  assert(strcmp(phnumGet(pnum, 0), "011") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "10021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20122");
  assert(strcmp(phnumGet(pnum, 0), "20122") == 0);
  phnumDelete(pnum);
  strcpy(num1, "200");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10222");
  assert(strcmp(phnumGet(pnum, 0), "10222") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0020");
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0101");
  assert(strcmp(phnumGet(pnum, 0), "0101") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "02121");
  pnum = phfwdGet(pf, "2202");
  assert(strcmp(phnumGet(pnum, 0), "2202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0002");
  strcpy(num1, "0011");
  strcpy(num2, "11001");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0112");
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "100") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22220");
  assert(strcmp(phnumGet(pnum, 0), "202220") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21020");
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "01") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "1011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2220");
  assert(strcmp(phnumGet(pnum, 0), "20220") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "102");
  strcpy(num2, "2001");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12");
  strcpy(num2, "1211");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "101");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11111");
  assert(strcmp(phnumGet(pnum, 0), "1011111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2010");
  strcpy(num2, "12102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11122");
  assert(strcmp(phnumGet(pnum, 0), "1011122") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "1011") == 0);
  phnumDelete(pnum);
  strcpy(num1, "012");
  strcpy(num2, "11220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "10202");
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  strcpy(num1, "00");
  strcpy(num2, "22");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0022");
  assert(strcmp(phnumGet(pnum, 0), "2222") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  strcpy(num1, "2221");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "000");
  assert(strcmp(phnumGet(pnum, 0), "000") == 0);
  phnumDelete(pnum);
  strcpy(num1, "110");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "01221");
  assert(strcmp(phnumGet(pnum, 0), "01221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2201");
  pnum = phfwdGet(pf, "20221");
  assert(strcmp(phnumGet(pnum, 0), "00221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1101");
  pnum = phfwdGet(pf, "22202");
  assert(strcmp(phnumGet(pnum, 0), "22202") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  strcpy(num1, "21110");
  strcpy(num2, "20012");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02202");
  assert(strcmp(phnumGet(pnum, 0), "02202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "11");
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "0");
  strcpy(num1, "01");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "211");
  assert(strcmp(phnumGet(pnum, 0), "211") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2001");
  assert(strcmp(phnumGet(pnum, 0), "0001") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20120");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "2000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "201");
  strcpy(num2, "202");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "0021");
  pnum = phfwdGet(pf, "00202");
  assert(strcmp(phnumGet(pnum, 0), "00202") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "220");
  assert(strcmp(phnumGet(pnum, 0), "220") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "1022");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10112");
  assert(strcmp(phnumGet(pnum, 0), "10112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "120");
  pnum = phfwdGet(pf, "10011");
  assert(strcmp(phnumGet(pnum, 0), "10011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "222");
  phfwdRemove(pf, "12100");
  phfwdRemove(pf, "21200");
  pnum = phfwdGet(pf, "202a");
  assert(phnumGet(pnum, 0) == NULL);
  phnumDelete(pnum);
  strcpy(num1, "21101");
  strcpy(num2, "00102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "122");
  strcpy(num1, "20");
  strcpy(num2, "212");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "102");
  phfwdRemove(pf, "222");
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "21121");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "211");
  assert(strcmp(phnumGet(pnum, 0), "2011") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "200");
  assert(strcmp(phnumGet(pnum, 0), "2000") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "100");
  phfwdRemove(pf, "202");
  strcpy(num1, "220");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00210");
  phfwdRemove(pf, "00");
  strcpy(num1, "0");
  strcpy(num2, "1120");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02201");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "0222");
  assert(strcmp(phnumGet(pnum, 0), "1120222") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "021");
  pnum = phfwdGet(pf, "21011");
  assert(strcmp(phnumGet(pnum, 0), "21011") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02111");
  assert(strcmp(phnumGet(pnum, 0), "11202111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00100");
  assert(strcmp(phnumGet(pnum, 0), "11200100") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12112");
  assert(strcmp(phnumGet(pnum, 0), "12112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "010");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1210");
  assert(strcmp(phnumGet(pnum, 0), "1210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10020");
  strcpy(num2, "001");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "012");
  strcpy(num2, "1220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "212");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "220");
  phfwdRemove(pf, "022");
  phfwdRemove(pf, "20002");
  phfwdRemove(pf, "211");
  strcpy(num1, "12012");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "020");
  assert(strcmp(phnumGet(pnum, 0), "020") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00100");
  phfwdRemove(pf, "011");
  strcpy(num1, "020");
  strcpy(num2, "0110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00002");
  strcpy(num2, "0200");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22002");
  assert(strcmp(phnumGet(pnum, 0), "0112002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "2011");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "201");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "101");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "122");
  assert(strcmp(phnumGet(pnum, 0), "122") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1020");
  strcpy(num2, "11101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0122");
  pnum = phfwdGet(pf, "0201");
  assert(strcmp(phnumGet(pnum, 0), "01101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "202");
  strcpy(num1, "2102");
  strcpy(num2, "200");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10010");
  assert(strcmp(phnumGet(pnum, 0), "10010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10022");
  strcpy(num2, "1121");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "0010");
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "0102");
  assert(strcmp(phnumGet(pnum, 0), "0102") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "2");
  strcpy(num2, "001");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1021");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "2120");
  phfwdRemove(pf, "1011");
  strcpy(num1, "022");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "0011") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22010");
  assert(strcmp(phnumGet(pnum, 0), "0012010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11121");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0020");
  strcpy(num2, "11012");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00220");
  strcpy(num1, "11021");
  strcpy(num2, "000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22122");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1111");
  assert(strcmp(phnumGet(pnum, 0), "1111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02101");
  assert(strcmp(phnumGet(pnum, 0), "02101") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02");
  strcpy(num2, "22110");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01011");
  assert(strcmp(phnumGet(pnum, 0), "01011") == 0);
  phnumDelete(pnum);
  strcpy(num1, "202");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "012");
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "0012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "01221");
  assert(strcmp(phnumGet(pnum, 0), "01221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "021");
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "11");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "220");
  strcpy(num1, "21221");
  strcpy(num2, "202");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00");
  strcpy(num1, "20");
  strcpy(num2, "0012");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  strcpy(num1, "012");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "221");
  assert(strcmp(phnumGet(pnum, 0), "221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0021");
  strcpy(num2, "22101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1222");
  assert(strcmp(phnumGet(pnum, 0), "1222") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "11");
  strcpy(num1, "12");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  strcpy(num1, "22222");
  strcpy(num2, "1011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1011");
  strcpy(num1, "00211");
  strcpy(num2, "21211");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "01222");
  phfwdRemove(pf, "22");
  strcpy(num1, "10");
  strcpy(num2, "0101");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20110");
  assert(strcmp(phnumGet(pnum, 0), "20110") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20220");
  pnum = phfwdGet(pf, "2221");
  assert(strcmp(phnumGet(pnum, 0), "2221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "12");
  phnumDelete(pnum);
  phfwdRemove(pf, "1012");
  phfwdRemove(pf, "221");
  phfwdRemove(pf, "12121");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "01010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1200");
  strcpy(num2, "1012");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "012");
  strcpy(num2, "12001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0020");
  assert(strcmp(phnumGet(pnum, 0), "0020") == 0);
  phnumDelete(pnum);
  strcpy(num1, "21212");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "102");
  strcpy(num1, "110");
  strcpy(num2, "211");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01100");
  assert(strcmp(phnumGet(pnum, 0), "01100") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02012");
  assert(strcmp(phnumGet(pnum, 0), "02012") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11");
  strcpy(num2, "0020");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "11202");
  strcpy(num2, "2101");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1110");
  strcpy(num2, "22221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "01") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "220");
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "21111");
  assert(strcmp(phnumGet(pnum, 0), "21111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "01000");
  assert(strcmp(phnumGet(pnum, 0), "01000") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "022");
  phfwdRemove(pf, "221");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02222");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "211");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "112");
  strcpy(num2, "121");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "211");
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  strcpy(num1, "212");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "120");
  assert(strcmp(phnumGet(pnum, 0), "120") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0202");
  assert(strcmp(phnumGet(pnum, 0), "0202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0222");
  phfwdRemove(pf, "222");
  pnum = phfwdGet(pf, "00000");
  assert(strcmp(phnumGet(pnum, 0), "00000") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "211");
  strcpy(num2, "0000");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "112");
  pnum = phfwdGet(pf, "1120");
  assert(strcmp(phnumGet(pnum, 0), "1120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "011");
  assert(strcmp(phnumGet(pnum, 0), "011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "021");
  assert(strcmp(phnumGet(pnum, 0), "021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "012");
  assert(strcmp(phnumGet(pnum, 0), "012") == 0);
  phnumDelete(pnum);
  strcpy(num1, "21");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00112");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "00");
  phfwdRemove(pf, "02102");
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "121");
  assert(strcmp(phnumGet(pnum, 0), "121") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12211");
  phfwdRemove(pf, "22");
  strcpy(num1, "2021");
  strcpy(num2, "02200");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12");
  phfwdRemove(pf, "0020");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00220");
  pnum = phfwdGet(pf, "2100");
  assert(strcmp(phnumGet(pnum, 0), "2100") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20101");
  assert(strcmp(phnumGet(pnum, 0), "20101") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2022");
  assert(strcmp(phnumGet(pnum, 0), "2022") == 0);
  phnumDelete(pnum);
  strcpy(num1, "022");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10002");
  strcpy(num1, "2020");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2202");
  assert(strcmp(phnumGet(pnum, 0), "2202") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02210");
  strcpy(num2, "2020");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1002");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "100");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "01112");
  assert(strcmp(phnumGet(pnum, 0), "01112") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "121");
  phfwdRemove(pf, "01201");
  phfwdRemove(pf, "2");
  strcpy(num1, "2");
  strcpy(num2, "11122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "21220");
  strcpy(num2, "100");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11");
  pnum = phfwdGet(pf, "2110");
  assert(strcmp(phnumGet(pnum, 0), "11122110") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "022");
  phfwdRemove(pf, "12");
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "21002") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20200");
  strcpy(num2, "1002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "00");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "111");
  strcpy(num1, "2211");
  strcpy(num2, "22101");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  phnumDelete(pnum);
  phfwdRemove(pf, "2222");
  strcpy(num1, "1");
  strcpy(num2, "00212");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "021");
  assert(strcmp(phnumGet(pnum, 0), "021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "100");
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "11212");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02201");
  assert(strcmp(phnumGet(pnum, 0), "02201") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "112");
  strcpy(num1, "222");
  strcpy(num2, "1210");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22010");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "020");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "022");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "220");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "00120");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0100");
  strcpy(num1, "0");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "001202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10100");
  strcpy(num2, "22");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "001202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12");
  pnum = phfwdGet(pf, "11002");
  assert(strcmp(phnumGet(pnum, 0), "11002") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12110");
  strcpy(num1, "11221");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "211");
  phfwdRemove(pf, "0022");
  phfwdRemove(pf, "02");
  phfwdRemove(pf, "20");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "100");
  strcpy(num2, "0020");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2120");
  pnum = phfwdGet(pf, "00222");
  assert(strcmp(phnumGet(pnum, 0), "1222") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "00110");
  assert(strcmp(phnumGet(pnum, 0), "00110") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "02110");
  phfwdRemove(pf, "01");
  phfwdRemove(pf, "00");
  phfwdRemove(pf, "0102");
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "12002");
  strcpy(num1, "1");
  strcpy(num2, "211");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "01");
  phfwdRemove(pf, "02");
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "2111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1100");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "121");
  strcpy(num1, "2");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "202");
  strcpy(num2, "1222");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0201");
  assert(strcmp(phnumGet(pnum, 0), "0201") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1021");
  pnum = phfwdGet(pf, "200");
  assert(strcmp(phnumGet(pnum, 0), "200") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21101");
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "21111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "01");
  assert(strcmp(phnumGet(pnum, 0), "01") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12200");
  assert(strcmp(phnumGet(pnum, 0), "2112200") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0001");
  strcpy(num1, "20");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1011");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "022") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1002");
  strcpy(num2, "1210");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "122");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "011");
  phfwdRemove(pf, "0");
  strcpy(num1, "02020");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0021");
  strcpy(num1, "0");
  strcpy(num2, "101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "011");
  strcpy(num1, "002");
  strcpy(num2, "1121");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10022");
  strcpy(num1, "11");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00220");
  assert(strcmp(phnumGet(pnum, 0), "112120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22121");
  strcpy(num1, "1000");
  strcpy(num2, "122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "01011");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2101");
  assert(strcmp(phnumGet(pnum, 0), "01011101") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "101");
  assert(strcmp(phnumGet(pnum, 0), "21101") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "11210");
  pnum = phfwdGet(pf, "11");
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  pnum = phfwdGet(pf, "20210");
  assert(strcmp(phnumGet(pnum, 0), "122210") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1011");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "2112") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0021");
  assert(strcmp(phnumGet(pnum, 0), "11211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01010");
  strcpy(num1, "0100");
  strcpy(num2, "00000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02211");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02101");
  pnum = phfwdGet(pf, "11");
  phnumDelete(pnum);
  strcpy(num1, "01a21");
  strcpy(num2, "12001");
  assert(phfwdAdd(pf, num1, num2) == false);
  strcpy(num1, "21a21");
  strcpy(num2, "1222");
  assert(phfwdAdd(pf, num1, num2) == false);
  strcpy(num1, "01022");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "2010");
  assert(strcmp(phnumGet(pnum, 0), "22010") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "020");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10020");
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "1022");
  phfwdRemove(pf, "00");
  strcpy(num1, "10");
  strcpy(num2, "12012");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "021");
  assert(strcmp(phnumGet(pnum, 0), "2121") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "2110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "222");
  strcpy(num2, "200");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "222");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21101") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "12001");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00");
  phfwdDelete(pf);
}
