#ifdef NDEBUG
#undef NDEBUG
#endif

#include "phone_forward.h"

#include <assert.h>
#include <string.h>

#define MAX_LEN 30
int main() {
  char num1[MAX_LEN + 1], num2[MAX_LEN + 1];
  PhoneForward *pf;
  PhoneNumbers *pnum;
  pf = phfwdNew();
  strcpy(num1, "0");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "11") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "010");
  assert(strcmp(phnumGet(pnum, 0), "110") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0221");
  strcpy(num2, "12111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "102") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12021");
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "11") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2210");
  assert(strcmp(phnumGet(pnum, 0), "2210") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22");
  strcpy(num1, "01");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1012");
  pnum = phfwdGet(pf, "2120");
  assert(strcmp(phnumGet(pnum, 0), "2120") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "11001");
  strcpy(num2, "20001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2221");
  assert(strcmp(phnumGet(pnum, 0), "2221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "100");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00010");
  phfwdRemove(pf, "20102");
  strcpy(num1, "2");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2011");
  strcpy(num1, "202");
  strcpy(num2, "1002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "201");
  assert(strcmp(phnumGet(pnum, 0), "0001") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "1021");
  assert(strcmp(phnumGet(pnum, 0), "021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "211");
  assert(strcmp(phnumGet(pnum, 0), "0011") == 0);
  phnumDelete(pnum);
  strcpy(num1, "201");
  strcpy(num2, "1022");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2000");
  phfwdRemove(pf, "12");
  strcpy(num1, "0012");
  strcpy(num2, "000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01010");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "21212");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10220");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2111");
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2100");
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "102") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "121");
  phfwdRemove(pf, "221");
  strcpy(num1, "22");
  strcpy(num2, "2001");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "021");
  strcpy(num2, "01011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12");
  strcpy(num1, "20110");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "210");
  strcpy(num1, "21");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1111");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2221");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21110");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "001");
  strcpy(num2, "2221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "0211");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "201");
  phnumDelete(pnum);
  strcpy(num1, "102");
  strcpy(num2, "12002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20221");
  assert(strcmp(phnumGet(pnum, 0), "100221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "210");
  strcpy(num2, "2121");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2010");
  strcpy(num2, "21002");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "1021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10200");
  assert(strcmp(phnumGet(pnum, 0), "1200200") == 0);
  phnumDelete(pnum);
  strcpy(num1, "101");
  strcpy(num2, "121");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "001");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2120");
  strcpy(num1, "102");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2011");
  pnum = phfwdGet(pf, "0021");
  assert(strcmp(phnumGet(pnum, 0), "102121") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2012");
  phfwdRemove(pf, "12");
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  strcpy(num1, "012");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00000");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0111");
  assert(strcmp(phnumGet(pnum, 0), "0111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  phnumDelete(pnum);
  strcpy(num1, "22012");
  strcpy(num2, "11101");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "011");
  assert(strcmp(phnumGet(pnum, 0), "011") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "020");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22101");
  strcpy(num2, "020");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01212");
  strcpy(num2, "0002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "021");
  pnum = phfwdGet(pf, "00122");
  assert(strcmp(phnumGet(pnum, 0), "00122") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "22212");
  assert(strcmp(phnumGet(pnum, 0), "12") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "111");
  strcpy(num1, "10");
  strcpy(num2, "1021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "120");
  assert(strcmp(phnumGet(pnum, 0), "120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "1210");
  strcpy(num2, "111");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "01102");
  phfwdRemove(pf, "110");
  phfwdRemove(pf, "001");
  phfwdRemove(pf, "0");
  strcpy(num1, "0002");
  strcpy(num2, "2201");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2122");
  phfwdRemove(pf, "0210");
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  strcpy(num1, "012");
  strcpy(num2, "1111");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0202");
  pnum = phfwdGet(pf, "11110");
  assert(strcmp(phnumGet(pnum, 0), "11110") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22121");
  assert(strcmp(phnumGet(pnum, 0), "22121") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2021");
  strcpy(num2, "2202");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22002");
  assert(strcmp(phnumGet(pnum, 0), "22002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1202");
  pnum = phfwdGet(pf, "1112");
  assert(strcmp(phnumGet(pnum, 0), "1112") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2021");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1220");
  assert(strcmp(phnumGet(pnum, 0), "1220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11");
  strcpy(num2, "12102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02012");
  assert(strcmp(phnumGet(pnum, 0), "02012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  strcpy(num1, "201");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  strcpy(num1, "22");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0202");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2212");
  strcpy(num1, "020");
  strcpy(num2, "101");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02221");
  assert(strcmp(phnumGet(pnum, 0), "02221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21");
  pnum = phfwdGet(pf, "012");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2010");
  assert(strcmp(phnumGet(pnum, 0), "2010") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22221");
  phfwdRemove(pf, "111");
  pnum = phfwdGet(pf, "222");
  assert(strcmp(phnumGet(pnum, 0), "012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11");
  phnumDelete(pnum);
  strcpy(num1, "2212");
  strcpy(num2, "1112");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10110");
  strcpy(num2, "0211");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "111");
  strcpy(num2, "222");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10");
  strcpy(num2, "2021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00211");
  assert(strcmp(phnumGet(pnum, 0), "00211") == 0);
  phnumDelete(pnum);
  strcpy(num1, "010");
  strcpy(num2, "2101");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02");
  strcpy(num2, "12202");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "202");
  phfwdRemove(pf, "2021");
  pnum = phfwdGet(pf, "20221");
  assert(strcmp(phnumGet(pnum, 0), "20221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "210");
  phfwdRemove(pf, "020");
  strcpy(num1, "20002");
  strcpy(num2, "100");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1010");
  strcpy(num1, "20");
  strcpy(num2, "0010");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  strcpy(num1, "20200");
  strcpy(num2, "0102");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02");
  strcpy(num2, "0001");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22002");
  pnum = phfwdGet(pf, "2111");
  assert(strcmp(phnumGet(pnum, 0), "2111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "002");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "21");
  strcpy(num2, "21022");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00");
  phfwdRemove(pf, "20");
  strcpy(num1, "00");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "0022");
  pnum = phfwdGet(pf, "02122");
  assert(strcmp(phnumGet(pnum, 0), "0001122") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01");
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "102") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2222");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20");
  strcpy(num2, "0221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "000");
  assert(strcmp(phnumGet(pnum, 0), "0110") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00212");
  strcpy(num1, "10");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20");
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "0011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2222");
  strcpy(num2, "00221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  phnumDelete(pnum);
  strcpy(num1, "120");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22222");
  phfwdRemove(pf, "1011");
  strcpy(num1, "221");
  strcpy(num2, "11111");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22211");
  strcpy(num2, "000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0102");
  strcpy(num2, "21111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "201");
  strcpy(num2, "1210");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0200");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "21");
  phnumDelete(pnum);
  phfwdRemove(pf, "011");
  strcpy(num1, "2001");
  strcpy(num2, "12201");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "2002");
  pnum = phfwdGet(pf, "222");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1a");
  strcpy(num2, "1102");
  assert(phfwdAdd(pf, num1, num2) == false);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "220");
  assert(strcmp(phnumGet(pnum, 0), "220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00201");
  phfwdRemove(pf, "211");
  phfwdRemove(pf, "2002");
  phfwdRemove(pf, "210");
  phfwdRemove(pf, "201");
  pnum = phfwdGet(pf, "00200");
  assert(strcmp(phnumGet(pnum, 0), "011200") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "2");
  strcpy(num1, "022");
  strcpy(num2, "2200");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1021");
  strcpy(num1, "0");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20010");
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1200");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20220");
  assert(strcmp(phnumGet(pnum, 0), "20220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0212");
  strcpy(num2, "122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22");
  strcpy(num2, "2020");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  strcpy(num1, "111");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1001");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1202");
  pnum = phfwdGet(pf, "200");
  assert(strcmp(phnumGet(pnum, 0), "200") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1001");
  strcpy(num2, "01120");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02210");
  assert(strcmp(phnumGet(pnum, 0), "220010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "011");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1121");
  assert(strcmp(phnumGet(pnum, 0), "1210221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "0100");
  assert(strcmp(phnumGet(pnum, 0), "0100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0102");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  strcpy(num1, "0");
  strcpy(num2, "0221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12022");
  phfwdRemove(pf, "11");
  pnum = phfwdGet(pf, "212");
  assert(strcmp(phnumGet(pnum, 0), "212") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12221");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "011a");
  strcpy(num1, "2221");
  strcpy(num2, "2002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "01111");
  strcpy(num1, "0");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "121");
  phfwdRemove(pf, "0120");
  pnum = phfwdGet(pf, "2120");
  assert(strcmp(phnumGet(pnum, 0), "2120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "202");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0020");
  strcpy(num1, "1011");
  strcpy(num2, "0200");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "201");
  assert(strcmp(phnumGet(pnum, 0), "0101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "1112");
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "002") == 0);
  phnumDelete(pnum);
  strcpy(num1, "120");
  strcpy(num2, "20002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "112");
  pnum = phfwdGet(pf, "21011");
  assert(strcmp(phnumGet(pnum, 0), "011011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  strcpy(num1, "01020");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0220");
  phfwdRemove(pf, "2010");
  pnum = phfwdGet(pf, "201");
  assert(strcmp(phnumGet(pnum, 0), "0101") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "211");
  assert(strcmp(phnumGet(pnum, 0), "0111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "10201");
  assert(strcmp(phnumGet(pnum, 0), "20201") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "200") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "220");
  assert(strcmp(phnumGet(pnum, 0), "0120") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01");
  pnum = phfwdGet(pf, "1212");
  assert(strcmp(phnumGet(pnum, 0), "1212") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22111");
  assert(strcmp(phnumGet(pnum, 0), "012111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "220");
  strcpy(num1, "222");
  strcpy(num2, "22");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02010");
  strcpy(num2, "010");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "1100");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2211");
  assert(strcmp(phnumGet(pnum, 0), "1100211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22011");
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "200");
  assert(strcmp(phnumGet(pnum, 0), "110000") == 0);
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "200");
  strcpy(num2, "0001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "102");
  assert(strcmp(phnumGet(pnum, 0), "102") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2112");
  assert(strcmp(phnumGet(pnum, 0), "1100112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "02021");
  phfwdRemove(pf, "01212");
  strcpy(num1, "00210");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1111");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0112");
  strcpy(num1, "00112");
  strcpy(num2, "21110");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  pnum = phfwdGet(pf, "2220");
  assert(strcmp(phnumGet(pnum, 0), "220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "111");
  strcpy(num2, "11221");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "200");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "2200");
  strcpy(num2, "22022");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12221");
  assert(strcmp(phnumGet(pnum, 0), "122221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "000");
  strcpy(num1, "122");
  strcpy(num2, "10210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02012");
  assert(strcmp(phnumGet(pnum, 0), "02012") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "1101a");
  assert(phfwdAdd(pf, num1, num2) == false);
  phfwdRemove(pf, "02");
  strcpy(num1, "22");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11111");
  phfwdRemove(pf, "01210");
  phfwdRemove(pf, "221");
  pnum = phfwdGet(pf, "1201");
  assert(strcmp(phnumGet(pnum, 0), "12201") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "022");
  strcpy(num2, "00200");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0000");
  strcpy(num2, "1201");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "02") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1122");
  strcpy(num1, "21122");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "120") == 0);
  phnumDelete(pnum);
  strcpy(num1, "01");
  strcpy(num2, "10201");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12010");
  strcpy(num2, "01112");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "02221");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "210");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  strcpy(num1, "0");
  strcpy(num2, "20210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2212");
  assert(strcmp(phnumGet(pnum, 0), "2212") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "122") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12020");
  assert(strcmp(phnumGet(pnum, 0), "122020") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "0102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "1010");
  phfwdRemove(pf, "10");
  strcpy(num1, "0010");
  strcpy(num2, "121");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "11121");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "002");
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "1001");
  phfwdRemove(pf, "21");
  pnum = phfwdGet(pf, "0220");
  assert(strcmp(phnumGet(pnum, 0), "002000") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2200");
  assert(strcmp(phnumGet(pnum, 0), "2200") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "222");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "112");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10202");
  assert(strcmp(phnumGet(pnum, 0), "120202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22011");
  strcpy(num1, "100");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "21");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11");
  strcpy(num1, "21202");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0100");
  pnum = phfwdGet(pf, "21");
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "22002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22");
  strcpy(num1, "0");
  strcpy(num2, "1021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "10212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "112");
  pnum = phfwdGet(pf, "10121");
  assert(strcmp(phnumGet(pnum, 0), "120121") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  strcpy(num1, "102");
  strcpy(num2, "1221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "121") == 0);
  phnumDelete(pnum);
  strcpy(num1, "00000");
  strcpy(num2, "22211");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "221");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "11122");
  assert(strcmp(phnumGet(pnum, 0), "121122") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "201");
  phfwdRemove(pf, "012");
  pnum = phfwdGet(pf, "20211");
  assert(strcmp(phnumGet(pnum, 0), "20211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0201");
  phfwdRemove(pf, "1122");
  pnum = phfwdGet(pf, "11112");
  assert(strcmp(phnumGet(pnum, 0), "121112") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2022");
  assert(strcmp(phnumGet(pnum, 0), "2022") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "121");
  assert(strcmp(phnumGet(pnum, 0), "1221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1122");
  strcpy(num2, "2220");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  strcpy(num1, "1210");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "012");
  pnum = phfwdGet(pf, "2020");
  assert(strcmp(phnumGet(pnum, 0), "2020") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12010");
  phnumDelete(pnum);
  phfwdRemove(pf, "212");
  strcpy(num1, "10");
  strcpy(num2, "21111");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "0021");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "112");
  phfwdRemove(pf, "20200");
  pnum = phfwdGet(pf, "2021");
  assert(strcmp(phnumGet(pnum, 0), "2021") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12201");
  strcpy(num2, "111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12210");
  assert(strcmp(phnumGet(pnum, 0), "1021010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "000");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "002");
  assert(strcmp(phnumGet(pnum, 0), "00212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "000");
  strcpy(num1, "01010");
  strcpy(num2, "21222");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20001");
  phfwdRemove(pf, "20211");
  pnum = phfwdGet(pf, "01021");
  assert(strcmp(phnumGet(pnum, 0), "01021") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "10010");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2200");
  assert(strcmp(phnumGet(pnum, 0), "10010200") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00000");
  phfwdRemove(pf, "0");
  strcpy(num1, "1");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0212");
  strcpy(num2, "122");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2112");
  strcpy(num1, "0");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "0012");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "20100");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  phfwdRemove(pf, "20202");
  phfwdRemove(pf, "12");
  pnum = phfwdGet(pf, "12001");
  assert(strcmp(phnumGet(pnum, 0), "0112001") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "22222");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20201");
  assert(strcmp(phnumGet(pnum, 0), "00120201") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "00210");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "22");
  phnumDelete(pnum);
  strcpy(num1, "20");
  strcpy(num2, "01220");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0102");
  phfwdRemove(pf, "2200");
  phfwdRemove(pf, "02001");
  strcpy(num1, "0");
  strcpy(num2, "12011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "212");
  strcpy(num1, "00021");
  strcpy(num2, "1100");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2220");
  pnum = phfwdGet(pf, "2100");
  assert(strcmp(phnumGet(pnum, 0), "0012100") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "11");
  pnum = phfwdGet(pf, "12212");
  assert(strcmp(phnumGet(pnum, 0), "12212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20");
  pnum = phfwdGet(pf, "0112");
  assert(strcmp(phnumGet(pnum, 0), "12011112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00");
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "11") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0a1");
  assert(phnumGet(pnum, 0) == NULL);
  phnumDelete(pnum);
  strcpy(num1, "1022");
  strcpy(num2, "220");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2121");
  assert(strcmp(phnumGet(pnum, 0), "0012121") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1000");
  assert(strcmp(phnumGet(pnum, 0), "1000") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "200");
  pnum = phfwdGet(pf, "00221");
  assert(strcmp(phnumGet(pnum, 0), "10221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "21102");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0111");
  assert(strcmp(phnumGet(pnum, 0), "1111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1221");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1111");
  assert(strcmp(phnumGet(pnum, 0), "1111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01002");
  pnum = phfwdGet(pf, "20021");
  assert(strcmp(phnumGet(pnum, 0), "00120021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "12") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10001");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2121");
  assert(strcmp(phnumGet(pnum, 0), "0012121") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2120");
  phfwdRemove(pf, "1111");
  strcpy(num1, "0");
  strcpy(num2, "2101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12120");
  phfwdRemove(pf, "122");
  pnum = phfwdGet(pf, "22");
  phnumDelete(pnum);
  phfwdRemove(pf, "121");
  strcpy(num1, "11110");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "002");
  strcpy(num1, "0001");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20122");
  assert(strcmp(phnumGet(pnum, 0), "00120122") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "001");
  strcpy(num2, "1101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2200");
  phfwdRemove(pf, "1200");
  pnum = phfwdGet(pf, "02");
  assert(strcmp(phnumGet(pnum, 0), "21012") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1101");
  strcpy(num2, "1222");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00100");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "211");
  assert(strcmp(phnumGet(pnum, 0), "001211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "101");
  strcpy(num1, "1");
  strcpy(num2, "0000");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "00001") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2220");
  strcpy(num1, "110");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02020");
  strcpy(num2, "0202");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0112");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12");
  strcpy(num2, "2001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "11");
  strcpy(num2, "012");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2100");
  strcpy(num2, "0220");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1221");
  strcpy(num1, "0");
  strcpy(num2, "1021");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20002");
  assert(strcmp(phnumGet(pnum, 0), "00120002") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "12012");
  assert(strcmp(phnumGet(pnum, 0), "2001012") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2211");
  phfwdRemove(pf, "020");
  strcpy(num1, "1");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1212");
  assert(strcmp(phnumGet(pnum, 0), "200112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01");
  phfwdRemove(pf, "0021");
  phfwdRemove(pf, "002");
  pnum = phfwdGet(pf, "2212");
  assert(strcmp(phnumGet(pnum, 0), "2212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0210");
  strcpy(num1, "21002");
  strcpy(num2, "1001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "02");
  strcpy(num2, "20202");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "202");
  strcpy(num2, "000");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1011");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12");
  pnum = phfwdGet(pf, "2100");
  assert(strcmp(phnumGet(pnum, 0), "2100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0120");
  strcpy(num2, "22001");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0012");
  strcpy(num1, "122");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02220");
  assert(strcmp(phnumGet(pnum, 0), "20202220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "01");
  strcpy(num2, "11102");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12122");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "01");
  phfwdRemove(pf, "11102");
  pnum = phfwdGet(pf, "10");
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "111");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "21022");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "120");
  assert(strcmp(phnumGet(pnum, 0), "11120") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0201");
  assert(strcmp(phnumGet(pnum, 0), "2020201") == 0);
  phnumDelete(pnum);
  strcpy(num1, "120");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "221");
  phfwdRemove(pf, "2");
  strcpy(num1, "21011");
  strcpy(num2, "0012");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "2102");
  assert(strcmp(phnumGet(pnum, 0), "2102") == 0);
  phnumDelete(pnum);
  strcpy(num1, "020");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2110");
  strcpy(num2, "21011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2120");
  pnum = phfwdGet(pf, "20110");
  assert(strcmp(phnumGet(pnum, 0), "20110") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "122");
  assert(strcmp(phnumGet(pnum, 0), "122") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "a01");
  assert(phnumGet(pnum, 0) == NULL);
  phnumDelete(pnum);
  strcpy(num1, "12021");
  strcpy(num2, "21010");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "200");
  strcpy(num2, "221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "111");
  strcpy(num1, "20220");
  strcpy(num2, "12111");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1102");
  strcpy(num2, "1111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22102");
  strcpy(num2, "021");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02022");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "12") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12220");
  strcpy(num2, "11102");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00");
  strcpy(num2, "11002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22");
  strcpy(num1, "10");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02010");
  assert(strcmp(phnumGet(pnum, 0), "11010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00211");
  assert(strcmp(phnumGet(pnum, 0), "11002211") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "100");
  assert(strcmp(phnumGet(pnum, 0), "100") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2012");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21122");
  phfwdRemove(pf, "2");
  strcpy(num1, "200");
  strcpy(num2, "211");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12");
  strcpy(num2, "120");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "10");
  strcpy(num2, "2212");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1102");
  phnumDelete(pnum);
  strcpy(num1, "21");
  strcpy(num2, "112");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12212");
  phfwdRemove(pf, "1");
  strcpy(num1, "0");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  phnumDelete(pnum);
  phfwdRemove(pf, "00000");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00010");
  assert(strcmp(phnumGet(pnum, 0), "11002010") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0112");
  strcpy(num1, "20021");
  strcpy(num2, "22002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02211");
  strcpy(num1, "012");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0202");
  strcpy(num2, "21111");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "22");
  strcpy(num1, "2");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "021");
  assert(strcmp(phnumGet(pnum, 0), "202021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "01100");
  strcpy(num1, "1112");
  strcpy(num2, "122");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02210");
  assert(strcmp(phnumGet(pnum, 0), "20202210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1210");
  strcpy(num2, "002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0122");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "02");
  phfwdRemove(pf, "1");
  strcpy(num1, "102");
  strcpy(num2, "22212");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2112");
  assert(strcmp(phnumGet(pnum, 0), "11212") == 0);
  phnumDelete(pnum);
  strcpy(num1, "00");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12120");
  pnum = phfwdGet(pf, "2121");
  assert(strcmp(phnumGet(pnum, 0), "11221") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "211");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "22");
  strcpy(num2, "1101");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "21011");
  assert(strcmp(phnumGet(pnum, 0), "112011") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20020");
  strcpy(num1, "1");
  strcpy(num2, "0122");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01222");
  assert(strcmp(phnumGet(pnum, 0), "222") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12012");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "012");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  phnumDelete(pnum);
  phfwdRemove(pf, "12211");
  phfwdRemove(pf, "0002");
  strcpy(num1, "2020");
  strcpy(num2, "12001");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "12");
  strcpy(num1, "112");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "1010");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12011");
  assert(strcmp(phnumGet(pnum, 0), "01222011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01111");
  pnum = phfwdGet(pf, "1202");
  assert(strcmp(phnumGet(pnum, 0), "0122202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0112");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02102");
  phfwdRemove(pf, "0011");
  pnum = phfwdGet(pf, "1");
  phnumDelete(pnum);
  phfwdRemove(pf, "11");
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "012211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "101");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "10");
  assert(strcmp(phnumGet(pnum, 0), "01220") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "121");
  assert(strcmp(phnumGet(pnum, 0), "012221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "121");
  pnum = phfwdGet(pf, "0222");
  assert(strcmp(phnumGet(pnum, 0), "222") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "01222") == 0);
  phnumDelete(pnum);
  strcpy(num1, "21012");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "211");
  strcpy(num1, "2110");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0221");
  assert(strcmp(phnumGet(pnum, 0), "221") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "22220");
  assert(strcmp(phnumGet(pnum, 0), "22220") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0001");
  strcpy(num1, "21110");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02000");
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "1");
  strcpy(num1, "222");
  strcpy(num2, "2202");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "00122");
  strcpy(num2, "212");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  strcpy(num1, "01");
  strcpy(num2, "11120");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "200");
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "1222");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0221");
  assert(strcmp(phnumGet(pnum, 0), "221") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "11") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00");
  strcpy(num1, "121");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "11100");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "20210");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2210");
  phfwdRemove(pf, "202");
  phfwdRemove(pf, "11011");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0002");
  assert(strcmp(phnumGet(pnum, 0), "02002") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "220");
  assert(strcmp(phnumGet(pnum, 0), "220") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11122");
  strcpy(num2, "0220");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "222");
  phfwdRemove(pf, "010");
  pnum = phfwdGet(pf, "21100");
  assert(strcmp(phnumGet(pnum, 0), "21100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "0220");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "0121");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02102");
  strcpy(num2, "11122");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1121");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1201");
  phfwdRemove(pf, "000");
  strcpy(num1, "1111");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "110");
  assert(strcmp(phnumGet(pnum, 0), "110") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2120");
  assert(strcmp(phnumGet(pnum, 0), "0121120") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0020");
  strcpy(num2, "22121");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "0");
  strcpy(num1, "0012");
  strcpy(num2, "202");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "011");
  assert(strcmp(phnumGet(pnum, 0), "011") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20");
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "11");
  phfwdRemove(pf, "0202");
  strcpy(num1, "1120");
  strcpy(num2, "20011");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2201");
  phfwdRemove(pf, "212");
  strcpy(num1, "12000");
  strcpy(num2, "020");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01002");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01121");
  assert(strcmp(phnumGet(pnum, 0), "01121") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1111");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2202");
  strcpy(num2, "111");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "100");
  phfwdRemove(pf, "111");
  pnum = phfwdGet(pf, "221");
  assert(strcmp(phnumGet(pnum, 0), "221") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "10210");
  assert(strcmp(phnumGet(pnum, 0), "10210") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "112");
  assert(strcmp(phnumGet(pnum, 0), "112") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11211");
  assert(strcmp(phnumGet(pnum, 0), "11211") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "221");
  strcpy(num1, "00022");
  strcpy(num2, "0101");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "112");
  pnum = phfwdGet(pf, "1012");
  assert(strcmp(phnumGet(pnum, 0), "1012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1222");
  assert(strcmp(phnumGet(pnum, 0), "1222") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0011");
  assert(strcmp(phnumGet(pnum, 0), "0011") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1111");
  strcpy(num1, "012");
  strcpy(num2, "1102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "021");
  strcpy(num1, "10");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "12111");
  assert(strcmp(phnumGet(pnum, 0), "12111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  strcpy(num1, "11");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "022");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1011");
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "220");
  pnum = phfwdGet(pf, "11122");
  assert(strcmp(phnumGet(pnum, 0), "2122") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20001");
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  strcpy(num1, "110");
  strcpy(num2, "221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "201");
  phfwdRemove(pf, "11");
  strcpy(num1, "2");
  strcpy(num2, "2102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "222");
  assert(strcmp(phnumGet(pnum, 0), "210222") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210210") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11110");
  assert(strcmp(phnumGet(pnum, 0), "11110") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11201");
  assert(strcmp(phnumGet(pnum, 0), "11201") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  strcpy(num1, "000");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "0220") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  strcpy(num1, "22");
  strcpy(num2, "20222");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20211");
  assert(strcmp(phnumGet(pnum, 0), "21020211") == 0);
  phnumDelete(pnum);
  strcpy(num1, "002");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "010");
  pnum = phfwdGet(pf, "0a020");
  assert(phnumGet(pnum, 0) == NULL);
  phnumDelete(pnum);
  strcpy(num1, "01");
  strcpy(num2, "00001");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  phfwdRemove(pf, "2000");
  phfwdRemove(pf, "012");
  strcpy(num1, "0");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "112");
  assert(strcmp(phnumGet(pnum, 0), "112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  strcpy(num1, "2");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01210");
  strcpy(num2, "1102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0222");
  pnum = phfwdGet(pf, "0002");
  assert(strcmp(phnumGet(pnum, 0), "0002") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1000");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12011");
  phfwdRemove(pf, "00");
  phfwdRemove(pf, "10212");
  pnum = phfwdGet(pf, "2");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "00002");
  assert(strcmp(phnumGet(pnum, 0), "00002") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "222");
  assert(strcmp(phnumGet(pnum, 0), "222") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "10");
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "021");
  assert(strcmp(phnumGet(pnum, 0), "021") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1011");
  strcpy(num2, "11");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1211");
  assert(strcmp(phnumGet(pnum, 0), "1211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21002");
  phfwdRemove(pf, "0120");
  pnum = phfwdGet(pf, "2122");
  assert(strcmp(phnumGet(pnum, 0), "2122") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12110");
  strcpy(num2, "100");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "01212");
  assert(strcmp(phnumGet(pnum, 0), "01212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22111");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "210");
  phfwdRemove(pf, "110");
  strcpy(num1, "01");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  phfwdRemove(pf, "211");
  pnum = phfwdGet(pf, "02010");
  assert(strcmp(phnumGet(pnum, 0), "02010") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12121");
  pnum = phfwdGet(pf, "21201");
  assert(strcmp(phnumGet(pnum, 0), "21201") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "20");
  pnum = phfwdGet(pf, "2222");
  assert(strcmp(phnumGet(pnum, 0), "2222") == 0);
  phnumDelete(pnum);
  strcpy(num1, "212");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2010");
  assert(strcmp(phnumGet(pnum, 0), "2010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0121");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "22") == 0);
  phnumDelete(pnum);
  strcpy(num1, "10");
  strcpy(num2, "12011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "10110");
  assert(strcmp(phnumGet(pnum, 0), "110") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "02001");
  phfwdRemove(pf, "20");
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "212");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "1221");
  assert(strcmp(phnumGet(pnum, 0), "1221") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "21");
  assert(strcmp(phnumGet(pnum, 0), "21") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2202");
  assert(strcmp(phnumGet(pnum, 0), "2202") == 0);
  phnumDelete(pnum);
  strcpy(num1, "22200");
  strcpy(num2, "11202");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "112");
  assert(strcmp(phnumGet(pnum, 0), "112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "201");
  phfwdRemove(pf, "22");
  strcpy(num1, "200");
  strcpy(num2, "01");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "212");
  strcpy(num2, "0002");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "022");
  strcpy(num2, "20");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "110");
  strcpy(num2, "100");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "121");
  pnum = phfwdGet(pf, "0001");
  assert(strcmp(phnumGet(pnum, 0), "0001") == 0);
  phnumDelete(pnum);
  strcpy(num1, "100");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2020");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "00") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12112");
  strcpy(num2, "00");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  phfwdRemove(pf, "21201");
  phfwdRemove(pf, "22");
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "12") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0120");
  assert(strcmp(phnumGet(pnum, 0), "020") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01221");
  strcpy(num1, "20120");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  pnum = phfwdGet(pf, "1212");
  assert(strcmp(phnumGet(pnum, 0), "1212") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "0001");
  assert(strcmp(phnumGet(pnum, 0), "0001") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "01121");
  assert(strcmp(phnumGet(pnum, 0), "0121") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0");
  phfwdRemove(pf, "22201");
  phfwdRemove(pf, "2");
  strcpy(num1, "002");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "11111");
  assert(strcmp(phnumGet(pnum, 0), "11111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "010");
  strcpy(num2, "020");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "211");
  pnum = phfwdGet(pf, "11012");
  assert(strcmp(phnumGet(pnum, 0), "11012") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "001");
  assert(strcmp(phnumGet(pnum, 0), "001") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "0112");
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "1");
  strcpy(num1, "02000");
  strcpy(num2, "02");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "220");
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "122");
  assert(strcmp(phnumGet(pnum, 0), "122") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2122");
  assert(strcmp(phnumGet(pnum, 0), "2122") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20");
  pnum = phfwdGet(pf, "0");
  assert(strcmp(phnumGet(pnum, 0), "0") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "12122");
  phfwdRemove(pf, "21201");
  strcpy(num1, "10210");
  strcpy(num2, "102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "001");
  assert(strcmp(phnumGet(pnum, 0), "001") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "22202");
  pnum = phfwdGet(pf, "01111");
  assert(strcmp(phnumGet(pnum, 0), "01111") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "1");
  strcpy(num1, "102");
  strcpy(num2, "21");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "20") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "20021");
  assert(strcmp(phnumGet(pnum, 0), "20021") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "11");
  assert(strcmp(phnumGet(pnum, 0), "11") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "2101");
  assert(strcmp(phnumGet(pnum, 0), "2101") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "01011");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  phfwdRemove(pf, "0111");
  pnum = phfwdGet(pf, "22022");
  assert(strcmp(phnumGet(pnum, 0), "22022") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "01112");
  assert(strcmp(phnumGet(pnum, 0), "21112") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "01020");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "210");
  assert(strcmp(phnumGet(pnum, 0), "210") == 0);
  phnumDelete(pnum);
  strcpy(num1, "100");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  strcpy(num1, "0");
  strcpy(num2, "1210");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1002");
  assert(strcmp(phnumGet(pnum, 0), "122") == 0);
  phnumDelete(pnum);
  strcpy(num1, "02");
  strcpy(num2, "2000");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "222");
  strcpy(num1, "012");
  strcpy(num2, "00021");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "10");
  phfwdRemove(pf, "2");
  strcpy(num1, "11");
  strcpy(num2, "01002");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02");
  phnumDelete(pnum);
  strcpy(num1, "2210");
  strcpy(num2, "1a2");
  assert(phfwdAdd(pf, num1, num2) == false);
  strcpy(num1, "011");
  strcpy(num2, "112");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "0202");
  phfwdRemove(pf, "222");
  strcpy(num1, "20");
  strcpy(num2, "122");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "2");
  assert(strcmp(phnumGet(pnum, 0), "2") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "101");
  assert(strcmp(phnumGet(pnum, 0), "101") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "101");
  strcpy(num1, "2");
  strcpy(num2, "0221");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "022");
  phfwdRemove(pf, "021");
  strcpy(num1, "1");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "02");
  strcpy(num1, "21");
  strcpy(num2, "210");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "02100");
  strcpy(num2, "02000");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "122");
  strcpy(num2, "21102");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "02211");
  assert(strcmp(phnumGet(pnum, 0), "011211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "220");
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "200");
  assert(strcmp(phnumGet(pnum, 0), "200") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "100");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2022");
  strcpy(num2, "10020");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "01");
  pnum = phfwdGet(pf, "00");
  assert(strcmp(phnumGet(pnum, 0), "12100") == 0);
  phnumDelete(pnum);
  strcpy(num1, "2");
  strcpy(num2, "10");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0210");
  assert(strcmp(phnumGet(pnum, 0), "01110") == 0);
  phnumDelete(pnum);
  strcpy(num1, "1");
  strcpy(num2, "21000");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "2");
  pnum = phfwdGet(pf, "11");
  phnumDelete(pnum);
  phfwdRemove(pf, "21");
  strcpy(num1, "211");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "112");
  strcpy(num1, "02");
  strcpy(num2, "0110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "012");
  strcpy(num2, "1");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "1200");
  assert(strcmp(phnumGet(pnum, 0), "10000") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "20021");
  strcpy(num1, "102");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "1");
  strcpy(num2, "0221");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "0");
  strcpy(num2, "1202");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2222");
  strcpy(num2, "011");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "12222");
  strcpy(num2, "110");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "201");
  assert(strcmp(phnumGet(pnum, 0), "201") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "22010");
  assert(strcmp(phnumGet(pnum, 0), "22010") == 0);
  phnumDelete(pnum);
  strcpy(num1, "12");
  strcpy(num2, "12");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "21");
  strcpy(num1, "1");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "112");
  assert(strcmp(phnumGet(pnum, 0), "010022") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "00121");
  pnum = phfwdGet(pf, "1111");
  assert(strcmp(phnumGet(pnum, 0), "0100211") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "120");
  strcpy(num1, "10");
  strcpy(num2, "1201");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "021");
  strcpy(num2, "01110");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "2");
  strcpy(num2, "002");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "11");
  phfwdRemove(pf, "200");
  phfwdRemove(pf, "2202");
  pnum = phfwdGet(pf, "0120");
  assert(strcmp(phnumGet(pnum, 0), "10") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "02");
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "222");
  phfwdRemove(pf, "00112");
  pnum = phfwdGet(pf, "1");
  assert(strcmp(phnumGet(pnum, 0), "1") == 0);
  phnumDelete(pnum);
  strcpy(num1, "01100");
  strcpy(num2, "01111");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20111");
  assert(strcmp(phnumGet(pnum, 0), "0020111") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "0");
  phnumDelete(pnum);
  phfwdRemove(pf, "12011");
  strcpy(num1, "11");
  strcpy(num2, "010");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdRemove(pf, "00121");
  pnum = phfwdGet(pf, "12");
  assert(strcmp(phnumGet(pnum, 0), "12") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "1");
  phfwdRemove(pf, "210");
  strcpy(num1, "2220");
  strcpy(num2, "221");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "20");
  assert(strcmp(phnumGet(pnum, 0), "0020") == 0);
  phnumDelete(pnum);
  pnum = phfwdGet(pf, "11202");
  assert(strcmp(phnumGet(pnum, 0), "11202") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "001");
  strcpy(num1, "10");
  strcpy(num2, "0");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "0121");
  assert(strcmp(phnumGet(pnum, 0), "11") == 0);
  phnumDelete(pnum);
  strcpy(num1, "020");
  strcpy(num2, "012");
  assert(phfwdAdd(pf, num1, num2) == true);
  strcpy(num1, "112");
  strcpy(num2, "1010");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "22");
  assert(strcmp(phnumGet(pnum, 0), "0022") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "21000");
  phfwdRemove(pf, "22022");
  phfwdRemove(pf, "2021");
  strcpy(num1, "21202");
  strcpy(num2, "1101");
  assert(phfwdAdd(pf, num1, num2) == true);
  pnum = phfwdGet(pf, "111");
  assert(strcmp(phnumGet(pnum, 0), "111") == 0);
  phnumDelete(pnum);
  phfwdRemove(pf, "101");
  strcpy(num1, "10122");
  strcpy(num2, "2");
  assert(phfwdAdd(pf, num1, num2) == true);
  phfwdDelete(pf);
}
